---
# tasks file for role-01
- name: task-01 - from role-01
  ansible.builtin.debug:
    msg: "Role Name - {{ role_name1 }} ; Task Name - {{ task_name1}} "

- name: task-02 - from role-01
  ansible.builtin.debug:
    msg: "Role Name - {{ role_name1 }} ; Task Name - {{ task_name2}} "
