---
- name:  play-01 - Gather facts for everyone
  hosts: all 
  gather_facts: false
  tasks:
    - name: Collect only network-related facts
      ansible.builtin.setup:
         gather_subset:
           - '!all'
           - '!min'
           - network
    - name: My IP, MAC details.
      ansible.builtin.debug:
        msg: "IP Address = {{ansible_default_ipv4.address }}  ; MAC Address = {{ansible_default_ipv4.macaddress}} "

